# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-06-05 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='地点')),
                ('pedestrian_flow', models.IntegerField(verbose_name='人流量')),
                ('is_overloading', models.BooleanField(verbose_name='是否超载')),
                ('abnormal_video', models.CharField(max_length=50, null=True, verbose_name='异常视频')),
                ('time', models.CharField(max_length=50, verbose_name='捕获时间')),
            ],
            options={
                'verbose_name_plural': '人流量',
                'ordering': ['-id'],
                'verbose_name': '人流量',
                'db_table': 'local_data',
            },
        ),
        migrations.CreateModel(
            name='security_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='姓名')),
                ('location', models.CharField(max_length=50, verbose_name='位置')),
                ('p_number', models.CharField(max_length=50, verbose_name='联系方式')),
                ('weixin', models.CharField(max_length=50, null=True, verbose_name='微信')),
            ],
            options={
                'verbose_name_plural': '安保人员',
                'ordering': ['id'],
                'verbose_name': '安保人员',
                'db_table': 'security_staff',
            },
        ),
        migrations.CreateModel(
            name='ThresholdValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_value_normal', models.IntegerField(verbose_name='正常人流阈值')),
                ('threshold_value_yellow', models.IntegerField(verbose_name='人流量黄色阈值')),
            ],
            options={
                'verbose_name_plural': '人流量阈值',
                'ordering': ['-id'],
                'verbose_name': '人流量阈值',
                'db_table': 'threshold_value',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('local', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('wechat', models.CharField(max_length=50, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
                'verbose_name': '用户',
            },
        ),
    ]
