
# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-06-03 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='\u5730\u70b9')),
                ('pedestrian_flow', models.IntegerField(verbose_name='\u4eba\u6d41\u91cf')),
                ('is_overloading', models.BooleanField(verbose_name='\u662f\u5426\u8d85\u8f7d')),
                ('abnormal_video', models.BinaryField(verbose_name='\u5f02\u5e38\u89c6\u9891')),
                ('time', models.CharField(max_length=50, verbose_name='\u6355\u83b7\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'local_data',
                'verbose_name': '\u4eba\u6d41\u91cf',
                'verbose_name_plural': '\u4eba\u6d41\u91cf',
            },
        ),
        migrations.CreateModel(
            name='human_traffic_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['c_time'],
                'verbose_name': '\u4eba\u6d41\u91cf',
                'verbose_name_plural': '\u5f53\u524d\u4eba\u6d41\u91cf',
            },
        ),
        migrations.CreateModel(
            name='security_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='\u59d3\u540d')),
                ('location', models.CharField(max_length=50, verbose_name='\u4f4d\u7f6e')),
                ('p_number', models.CharField(max_length=50, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('weixin', models.CharField(max_length=50, null=True, verbose_name='\u5fae\u4fe1')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'security_staff',
                'verbose_name': '\u5b89\u4fdd\u4eba\u5458',
                'verbose_name_plural': '\u5b89\u4fdd\u4eba\u5458',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
